sudo: required

language: node_js
node_js:
  - "6"

services:
  - docker

script:
  - docker build -f Dockerfile -t kinglike/docker-hub-rss .
  - docker build -f Dockerfile.armhf -t kinglike/docker-hub-rss .
