FROM resin/raspberry-pi-alpine-node:8-slim

RUN [ "cross-build-start" ]

RUN apk add --no-cache git

WORKDIR /app

COPY yarn.lock /app
COPY package.json /app
RUN yarn install

COPY . /app

EXPOSE 3000

CMD yarn start

RUN [ "cross-build-end" ] 
